# Example AIP Policy Manifest
#
# This file defines what tools an agent is allowed to use.
# The AIP proxy loads this file at startup and enforces these rules
# on every tool/call request.
#
# Usage:
#   aip-proxy --target "python mcp_server.py" --policy examples/agent.yaml

apiVersion: aip.io/v1alpha1
kind: AgentPolicy

metadata:
  name: code-review-agent
  version: "1.0.0"
  owner: platform-team@company.com

spec:
  # Tools that this agent is allowed to invoke.
  # Any tool not in this list will be blocked with a -32001 Forbidden error.
  #
  # Tool names should match exactly what the MCP server reports in tools/list.
  # Common patterns:
  #   - github_get_repo, github_list_pulls, github_create_review
  #   - postgres_query
  #   - slack_post_message
  allowed_tools:
    # GitHub read operations
    - github_get_repo
    - github_list_pulls
    - github_get_pull
    - github_list_commits
    
    # GitHub write operations (limited)
    - github_create_review
    - github_add_comment
    
    # Filesystem operations (read-only)
    - read_file
    - list_directory
    
    # Explicitly NOT allowed (for reference):
    # - github_delete_repo      # Destructive
    # - github_push             # Write to repo
    # - postgres_query          # Database access
    # - slack_post_message      # External communication
    # - exec_command            # Arbitrary code execution
